stages:
- name: Build
  steps:
    - runScriptConfig:
        image: maven:3-jdk-8
        shellScript: |
          tee /settings.xml <<EOF
<settings>
  <mirrors>
    <mirror>
      <mirrorOf>central</mirrorOf>
      <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
    </mirror>
  </mirrors>
</settings>
EOF
          mvn -s /settings.xml clean package
- name: Publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: fullj/pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
        pushRemote: true
        registry: registry.cn-hangzhou.aliyuncs.com
      env:
        PLUGIN_MIRROR: https://d6izfrb6.mirror.aliyuncs.com
- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./deployment.yml

timeout: 8
