stages:
- name: Build
  steps:
    - runScriptConfig:
        image: maven:3-jdk-8
        shellScript: |-
          mkdir -p /opt/maven
          touch /opt/maven.settings.xml
          echo "<settings><mirrors><mirror><id>nexus-aliyun</id><url>https://maven.aliyun.com/nexus/content/groups/public/</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>" /opt/maven/settings.xml
          mvn --settings /opt/maven/settings.xml clean package
# no effect
#        volumeMounts:
#          - mountPath: /opt/maven
#            name: app-vol
#      volumes:
#        - name: app-vol
#          configMap:
#            name: maven-settings
#            items:
#              - key: settings.xml
#                path: ./settings.xml
- name: Publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: wrh/pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
        pushRemote: true
        registry: registry.cn-hangzhou.aliyuncs.com
      env:
        PLUGIN_MIRROR: https://d6izfrb6.mirror.aliyuncs.com
- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./deployment.yml