kind: Service
apiVersion: v1
metadata:
  name: example-spring-service
spec:
  selector:
    app: example-spring
  type: NodePort
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-spring-deployment
  labels:
    app: example-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-spring
  template:
    metadata:
      labels:
        app: example-spring
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      initContainers:
      - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: jar
        command: ["cp", "/app.jar", "/app"]
        volumeMounts:
        - mountPath: /app
          name: app-vol
      containers:
      - image: openjdk:8-alpine
        name: example-spring
        command: ["java", "-jar", "/app/app.jar"]
        volumeMounts:
        - mountPath: /app
          name: app-vol
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 3
      volumes:
      - name: app-vol
        emptyDir: {}
