kind: Service
apiVersion: v1
metadata:
  name: pipeline-example-spring-service
spec:
  selector:
    app: example-spring-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-example-spring-server
  labels:
    app: example-spring-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-spring-server
  template:
    metadata:
      labels:
        app: example-spring-server
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: example-spring-server
          image: registry.cn-hangzhou.aliyuncs.com/wrh/pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080