kind: Service
apiVersion: v1
metadata:
  name: pipeline-example-spring-service
spec:
  selector:
    app: example-spring-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-example-spring-server
  labels:
    app: example-spring-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-spring-server
  template:
    metadata:
      labels:
        app: example-spring-server
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      initContainers:
        - image: registry.cn-hangzhou.aliyuncs.com/wrh/pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
          name: jar
          command: ["cp", "/app.jar", "/app"]
          volumeMounts:
            - mountPath: /app
              name: app-vol
      containers:
        - image: openjdk:8-alpine
          name: example-spring-server
          command: ["java", "-jar", "/app/app.jar"]
            - mountPath: /app
          ports:
            - containerPort: 8080
              name: app-vol
      volumes:
        - name: app-vol
          emptyDir: {}